version: '3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      # ports:
      #   - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        - yc_pgdata:/var/lib/postgresql/data/

    nginx_yc:
        container_name: yc_nginx
        build: ./nginx
        restart: always
        ports:
        # - "8080:80"
        - "8101:80"
        volumes:
        - yc_api_data:/docker_api
        - ./log:/var/log/nginx
        depends_on:
        - api4

    api_yc:
        container_name: yc_django_blog
        build: ./YcBlog
        restart: always
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        # ports:
        # - "8002:8000"
        volumes:
        - yc_api_data:/docker_api
        depends_on:
        - db

    # auto migrate django
    # migration:
    #     build: ./api
    #     command:
    #         - /bin/sh
    #         - -c
    #         - |
    #           python manage.py collectstatic --noinput
    #           python manage.py migrate
    #           python manage.py makemigrations musics
    #           python manage.py migrate
    #     volumes:
    #     - api_data:/docker_api
    #     depends_on:
    #     - db

volumes:
    yc_api_data
    yc_pgdata

